Algoritmo "exerc3"
//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando
//no final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
Var
nome: caractere
sal: real
Inicio
escreva("Nome do Funcionário: ")
leia (nome)
escreva("Salário: ")
leia(sal)
escreva("O funcionário ", nome," tem um salário de R$", sal," em Junho.")
Fimalgoritmo