Algoritmo "exerc5"
//5) Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5
Var
nota1, nota2, media: real
Inicio
escreva("Nota 1: ")
leia(nota1)
escreva("Nota 2: ")
leia(nota2)
media<- (nota1 + nota2)/2
escreva("A média entre ",nota1," e ",nota2," é igual a ", media)
Fimalgoritmo