Algoritmo "exerc4"
//4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.
Var
num1, num2, soma: real
Inicio
escreva("Digite um valor: ")
leia(num1)
escreva("Digite outro valor: ")
leia(num2)
soma<-num1+num2
escreva("A soma entre",num1," e ",num2," é igual a ",soma,".")
Fimalgoritmo